# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20181106_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('productos', models.ManyToManyField(to='modelo.Producto')),
            ],
        ),
    ]
